#!/usr/bin/env node

const { Client } = require('pg');

const clientSettings = { database: 'ls_185_02' };
const client = new Client(clientSettings);

app();

function app() {
  const args = process.argv;

  if (args.length < 3) return logHelpContent();

  const command = args[2].trim().toLowerCase();

  switch (command) {
    case 'list':
      execListCommand();
      break;
    case 'add':
      execAddCommand();
      break;
    default:
      logHelpContent();
  };
};

async function execListCommand() {
  const expensesQuery = 'SELECT id, created_on, amount, memo FROM expenses ORDER BY created_on ASC';
  
  await client.connect();

  let expensesData = await client.query(expensesQuery);
  expensesData.rows.forEach(expenseRecord => logExpenseRow(expenseRecord))

  await client.end();
}

async function execAddCommand() {
  let commandArgs = getCommandArgs();
  if (commandArgs.length === 0) return logErrorNoAmountMemo();
  
  let [amount, memo] =  commandArgs;
  if (invalidAmount(amount)) return logInvalidAmount();
  if (invalidMemo(memo)) return logInvalidMemo();

  let additionQuery = `INSERT INTO expenses(amount, memo) VALUES (${amount}, '${memo}')`;
  console.log(additionQuery);
  
  await client.connect();
  await client.query(additionQuery);
  await client.end();
}

function getCommandArgs() {
  const MIN_LENGTH = 4;

  return process.argv.slice(MIN_LENGTH - 1) || [];
}

function logExpenseRow(expenseRecord) {
  let { id, created_on, amount, memo } = expenseRecord;

  let column1 = String(id).padStart(3, " ");
  let column2 = `${created_on.toDateString()}`;
  let column3 = String(amount).padStart(12, " ");
  let column4 = memo;

  console.log([column1, column2, column3, column4].join(' | '));
};

function invalidAmount(amount) {
  return Number.isNaN(amount);
};

function invalidMemo(memo) {
  console.log(memo)
  console.log(typeof memo);
  return typeof memo !== 'string';
};

function logErrorNoAmountMemo() {
  console.log('You must provide an amount and memo.');
};

function logInvalidAmount() {
  console.log('You must provide a valid amount.');
};

function logInvalidMemo() {
  console.log('You must provide a valid memo.');
};

function logHelpContent() {
  let helpContent = `An expense recording system

Commands:

add AMOUNT MEMO [DATE] - record a new expense
clear - delete all expenses
list - list all expenses
delete NUMBER - remove expense with id NUMBER
search QUERY - list expenses with a matching memo field`;

  console.log(helpContent)
};